// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VentasSD.Contexto;

#nullable disable

namespace VentasSD.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20251218005529_primera")]
    partial class primera
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("VentasSD.Models.Articulo", b =>
                {
                    b.Property<int>("IdArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Eslogan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMarca")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recomendaciones")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoArticulo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdArticulo");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdTipo");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("VentasSD.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Frecuente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("VentasSD.Models.Credito", b =>
                {
                    b.Property<int>("IdCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasColumnType("TEXT");

                    b.HasKey("IdCredito");

                    b.HasIndex("IdCliente");

                    b.ToTable("Creditos");
                });

            modelBuilder.Entity("VentasSD.Models.DetalleOrden", b =>
                {
                    b.Property<int>("IdDetalleOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdOrden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.HasKey("IdDetalleOrden");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdOrden");

                    b.ToTable("DetalleOrdenes");
                });

            modelBuilder.Entity("VentasSD.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Cargo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sueldo")
                        .HasColumnType("TEXT");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("VentasSD.Models.Envio", b =>
                {
                    b.Property<int>("IdEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaEntrega")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdTransporte")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PagoIncluido")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdEnvio");

                    b.HasIndex("IdTransporte");

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("VentasSD.Models.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DetalleOrdenIdDetalleOrden")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmpleadoIdEmpleado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioIngreso")
                        .HasColumnType("TEXT");

                    b.HasKey("IdInventario");

                    b.HasIndex("DetalleOrdenIdDetalleOrden");

                    b.HasIndex("EmpleadoIdEmpleado");

                    b.HasIndex("IdArticulo");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("VentasSD.Models.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("IdMarca");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("VentasSD.Models.Material", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdMaterial");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("VentasSD.Models.MaterialArticulo", b =>
                {
                    b.Property<int>("IdMaterialArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdMaterialArticulo");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdMaterial");

                    b.ToTable("MaterialArticulos");
                });

            modelBuilder.Entity("VentasSD.Models.Orden", b =>
                {
                    b.Property<int>("IdOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConEnvio")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmpleadoIdEmpleado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCredito")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEnvio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pago")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("IdOrden");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("EmpleadoIdEmpleado");

                    b.HasIndex("IdCredito");

                    b.HasIndex("IdEnvio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("VentasSD.Models.Talla", b =>
                {
                    b.Property<int>("IdTalla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdTalla");

                    b.ToTable("Tallas");
                });

            modelBuilder.Entity("VentasSD.Models.TallaArticulo", b =>
                {
                    b.Property<int>("IdTallaArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTalla")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTallaArticulo");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdTalla");

                    b.ToTable("TallaArticulos");
                });

            modelBuilder.Entity("VentasSD.Models.TallaTipo", b =>
                {
                    b.Property<int>("IdTallaTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTalla")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTallaTipo");

                    b.HasIndex("IdTalla");

                    b.HasIndex("IdTipo");

                    b.ToTable("TallaTipos");
                });

            modelBuilder.Entity("VentasSD.Models.Tipo", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdTipo");

                    b.ToTable("Tipos");
                });

            modelBuilder.Entity("VentasSD.Models.TipoMaterial", b =>
                {
                    b.Property<int>("IdTipoMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTipoMaterial");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdTipo");

                    b.ToTable("TipoMateriales");
                });

            modelBuilder.Entity("VentasSD.Models.TipoPago", b =>
                {
                    b.Property<int>("IdTipoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Comprobante")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCredito")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdOrden")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTipoPago");

                    b.HasIndex("IdCredito");

                    b.HasIndex("IdOrden");

                    b.ToTable("TipoPagos");
                });

            modelBuilder.Entity("VentasSD.Models.Transporte", b =>
                {
                    b.Property<int>("IdTransporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTransporte");

                    b.ToTable("Transportes");
                });

            modelBuilder.Entity("VentasSD.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("VentasSD.Models.Articulo", b =>
                {
                    b.HasOne("VentasSD.Models.Marca", "Marca")
                        .WithMany("Articulos")
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentasSD.Models.Tipo", "Tipo")
                        .WithMany("Articulos")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("VentasSD.Models.Cliente", b =>
                {
                    b.HasOne("VentasSD.Models.Usuario", "Usuario")
                        .WithMany("Clientes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VentasSD.Models.Credito", b =>
                {
                    b.HasOne("VentasSD.Models.Cliente", "Cliente")
                        .WithMany("Creditos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("VentasSD.Models.DetalleOrden", b =>
                {
                    b.HasOne("VentasSD.Models.Articulo", "Articulo")
                        .WithMany("DetallaOrdenes")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentasSD.Models.Orden", "Orden")
                        .WithMany("DetalleOrdenes")
                        .HasForeignKey("IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("VentasSD.Models.Empleado", b =>
                {
                    b.HasOne("VentasSD.Models.Usuario", "Usuario")
                        .WithMany("Empleados")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VentasSD.Models.Envio", b =>
                {
                    b.HasOne("VentasSD.Models.Transporte", "Transporte")
                        .WithMany("Envios")
                        .HasForeignKey("IdTransporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("VentasSD.Models.Inventario", b =>
                {
                    b.HasOne("VentasSD.Models.DetalleOrden", null)
                        .WithMany("Inventarios")
                        .HasForeignKey("DetalleOrdenIdDetalleOrden");

                    b.HasOne("VentasSD.Models.Empleado", null)
                        .WithMany("Inventarios")
                        .HasForeignKey("EmpleadoIdEmpleado");

                    b.HasOne("VentasSD.Models.Articulo", "Articulo")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("VentasSD.Models.MaterialArticulo", b =>
                {
                    b.HasOne("VentasSD.Models.Articulo", "Articulo")
                        .WithMany("MaterialArticulos")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentasSD.Models.Material", "Material")
                        .WithMany("MaterialArticulos")
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("VentasSD.Models.Orden", b =>
                {
                    b.HasOne("VentasSD.Models.Cliente", null)
                        .WithMany("Ordenes")
                        .HasForeignKey("ClienteIdCliente");

                    b.HasOne("VentasSD.Models.Empleado", null)
                        .WithMany("Ordenes")
                        .HasForeignKey("EmpleadoIdEmpleado");

                    b.HasOne("VentasSD.Models.Credito", "Credito")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdCredito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentasSD.Models.Envio", "Envio")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdEnvio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentasSD.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credito");

                    b.Navigation("Envio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VentasSD.Models.TallaArticulo", b =>
                {
                    b.HasOne("VentasSD.Models.Articulo", "Articulo")
                        .WithMany("TallaArticulos")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentasSD.Models.Talla", "Talla")
                        .WithMany("TallaArticulos")
                        .HasForeignKey("IdTalla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Talla");
                });

            modelBuilder.Entity("VentasSD.Models.TallaTipo", b =>
                {
                    b.HasOne("VentasSD.Models.Talla", "Talla")
                        .WithMany("TallaTipos")
                        .HasForeignKey("IdTalla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentasSD.Models.Tipo", "Tipo")
                        .WithMany("TallaTipos")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talla");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("VentasSD.Models.TipoMaterial", b =>
                {
                    b.HasOne("VentasSD.Models.Material", "Material")
                        .WithMany("TipoMaterials")
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentasSD.Models.Tipo", "Tipo")
                        .WithMany("TipoMateriales")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("VentasSD.Models.TipoPago", b =>
                {
                    b.HasOne("VentasSD.Models.Credito", "Credito")
                        .WithMany("TipoPagos")
                        .HasForeignKey("IdCredito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentasSD.Models.Orden", "Orden")
                        .WithMany("TipoPagos")
                        .HasForeignKey("IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credito");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("VentasSD.Models.Articulo", b =>
                {
                    b.Navigation("DetallaOrdenes");

                    b.Navigation("Inventarios");

                    b.Navigation("MaterialArticulos");

                    b.Navigation("TallaArticulos");
                });

            modelBuilder.Entity("VentasSD.Models.Cliente", b =>
                {
                    b.Navigation("Creditos");

                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("VentasSD.Models.Credito", b =>
                {
                    b.Navigation("Ordenes");

                    b.Navigation("TipoPagos");
                });

            modelBuilder.Entity("VentasSD.Models.DetalleOrden", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("VentasSD.Models.Empleado", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("VentasSD.Models.Envio", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("VentasSD.Models.Marca", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("VentasSD.Models.Material", b =>
                {
                    b.Navigation("MaterialArticulos");

                    b.Navigation("TipoMaterials");
                });

            modelBuilder.Entity("VentasSD.Models.Orden", b =>
                {
                    b.Navigation("DetalleOrdenes");

                    b.Navigation("TipoPagos");
                });

            modelBuilder.Entity("VentasSD.Models.Talla", b =>
                {
                    b.Navigation("TallaArticulos");

                    b.Navigation("TallaTipos");
                });

            modelBuilder.Entity("VentasSD.Models.Tipo", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("TallaTipos");

                    b.Navigation("TipoMateriales");
                });

            modelBuilder.Entity("VentasSD.Models.Transporte", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("VentasSD.Models.Usuario", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
