// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VentasSD.Contexto;

#nullable disable

namespace VentasSD.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("VentasSD.Models.Articulo", b =>
                {
                    b.Property<int>("IdArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Dirección")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Frecuente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMarca")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("IdArticulo");

                    b.HasIndex("IdMarca");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("VentasSD.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("VentasSD.Models.Empleado", b =>
                {
                    b.Property<int>("IdArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("IdArticulo");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("VentasSD.Models.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("IdMarca");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("VentasSD.Models.Material", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdMaterial");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("VentasSD.Models.MaterialArticulo", b =>
                {
                    b.Property<int>("IdMaterialArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdMaterialArticulo");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdMaterial");

                    b.ToTable("MaterialArticulo");
                });

            modelBuilder.Entity("VentasSD.Models.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Envio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pago")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("VentasSD.Models.Talla", b =>
                {
                    b.Property<int>("IdTalla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdTalla");

                    b.ToTable("Tallas");
                });

            modelBuilder.Entity("VentasSD.Models.TallaArticulo", b =>
                {
                    b.Property<int>("IdTallalArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTalla")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTallalArticulo");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdTalla");

                    b.ToTable("TallaArticulos");
                });

            modelBuilder.Entity("VentasSD.Models.TallaTipo", b =>
                {
                    b.Property<int>("IdTallaTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTalla")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTallaTipo");

                    b.HasIndex("IdTalla");

                    b.ToTable("TallaTipos");
                });

            modelBuilder.Entity("VentasSD.Models.TipoMaterial", b =>
                {
                    b.Property<int>("IdTipoMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTipoMaterial");

                    b.HasIndex("IdMaterial");

                    b.ToTable("tipoMaterials");
                });

            modelBuilder.Entity("VentasSD.Models.Articulo", b =>
                {
                    b.HasOne("VentasSD.Models.Marca", "Marca")
                        .WithMany("Articulos")
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("VentasSD.Models.MaterialArticulo", b =>
                {
                    b.HasOne("VentasSD.Models.Articulo", "Articulo")
                        .WithMany("MaterialArticulos")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentasSD.Models.Material", "Material")
                        .WithMany("MaterialArticulos")
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("VentasSD.Models.Orden", b =>
                {
                    b.HasOne("VentasSD.Models.Cliente", "Cliente")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("VentasSD.Models.TallaArticulo", b =>
                {
                    b.HasOne("VentasSD.Models.Articulo", "Articulo")
                        .WithMany("TallaArticulos")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentasSD.Models.Talla", "Talla")
                        .WithMany("TallaArtculos")
                        .HasForeignKey("IdTalla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Talla");
                });

            modelBuilder.Entity("VentasSD.Models.TallaTipo", b =>
                {
                    b.HasOne("VentasSD.Models.Talla", "Talla")
                        .WithMany("TallaTipos")
                        .HasForeignKey("IdTalla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talla");
                });

            modelBuilder.Entity("VentasSD.Models.TipoMaterial", b =>
                {
                    b.HasOne("VentasSD.Models.Material", "Material")
                        .WithMany("TipoMaterials")
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("VentasSD.Models.Articulo", b =>
                {
                    b.Navigation("MaterialArticulos");

                    b.Navigation("TallaArticulos");
                });

            modelBuilder.Entity("VentasSD.Models.Cliente", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("VentasSD.Models.Marca", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("VentasSD.Models.Material", b =>
                {
                    b.Navigation("MaterialArticulos");

                    b.Navigation("TipoMaterials");
                });

            modelBuilder.Entity("VentasSD.Models.Talla", b =>
                {
                    b.Navigation("TallaArtculos");

                    b.Navigation("TallaTipos");
                });
#pragma warning restore 612, 618
        }
    }
}
